### ISSUE TITLE
Wrong version with happypack

### ISSUE THREAD

**Issue by david-ogalego** [shakacode/sass-resources-loader#65]
We are trying to use the loader with [happypack ](https://github.com/amireh/happypack) and we see that there is a problem with version. 

We have seen the next code in sass-resources-loader/src/loader.js:

`var webpack = this; var isModernWebpack = webpack.version >= 2;`

Will always be the webpack version? or is it the loader version?

**Comment by justin808** [comment]
Try version 1.3.3 and please ask to reopen if not working.

**Comment by Mitjan11** [comment]
@justin808 

This is currently still an issue. This because HappyPack [provides a fake loader context which has an explicit version set to 1](https://github.com/amireh/happypack/issues/221) (no idea as to why).

However, the original creator of this issue also created a PR to fix this issue by removing the check from the code in this project (which seemed to be a TODO for webpack v2 stable anyway). See #66 

Any idea if this can be merged soon?
